spring:
  application:
    name: gateway
  # security layer

  # Data Layer

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

      routes:
        - id: projects
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/projects/**
          filters:
            - TokenRelay
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
