spring:
  application:
    name: ci-pipeline-gateway-${random.uuid}
  # security layer

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.f4d28dae012cb15c
            client-secret: 012375c85406b3efa3a11ff3e2f97bec858dbfcd
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthorizationUri: https://github.com/login/oauth/authorize
            clientAuthenticationScheme: form
            scope: public_repo, write:repo_hook, read:user, user:email
        provider:
          github:
            userInfoUri: https://api.github.com/user
            preferTokenInfo: false

  # Data Layer

  data:
    mongodb:
      host: localhost
      port: 27017
      database: pipeline
      username: root
      password: test
  main:
    allow-bean-definition-overriding: true

