server:
  port: 8082

spring:
  application:
    name: project-service-${random.uuid}

  data:
    mongodb:
      host: localhost
      port: 27017
      database: pipeline
      username: root
      password: test


