server:
  port: 8082

spring:
  application:
    name: project-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: test

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
