server:
  port: 8082

spring:
  application:
    name: project-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: test

#  security:
    oauth2:

      client:
        registration:
          github:
            client-id: Iv1.f4d28dae012cb15c
            client-secret: 7ee58e7018ef04218c7da560505176a2d395e7aa
            redirect-uri: https://localhost:8082/login/oauth2/code/github
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthorizationUri: https://github.com/login/oauth/authorize
            clientAuthenticationScheme: form
        provider:
          github:
            user-info-uri: https://api.github.com/user
            prefer-token-info: false

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
